name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Install Dependencies
      run: composer install
      
    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: sail up
      run: ./vendor/bin/sail up -d
      
    - name: Build, tag, and push image to Amazon ECR
      run: |
        ./vendor/bin/sail build
        docker tag sail-8.2/app:latest 637423528396.dkr.ecr.ap-northeast-2.amazonaws.com/tamago-laravel:latest
        docker push 637423528396.dkr.ecr.ap-northeast-2.amazonaws.com/tamago-laravel:latest

    - name: sail down
      run: ./vendor/bin/sail down
